Pin down Jinja2 to 3.0.3 when running in Python 3.x
With latest Jinja2-3.1.0 'rstcheck CHANGES.rst' fails with error:
  sphinx.errors.ExtensionError: Could not import extension
  sphinx.builders.latex (exception: cannot import name 'contextfunction'
   from 'jinja2')

According Jinja changelog 'contextfunction' has been deprecated
and it is removed in 3.1.0