WIP: Add support for Python 3.11
Invoke 0.12.2 doesn't work under Python 3.11, we need to upgrade
to avoid errors like:

AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?